### ISSUE TITLE
Vertaisarviointi 1

### ISSUE THREAD

**Issue by TopiasHarjunpaa** [toniramo/tso-harjoitustyo#1]
**Yleistä**

- Sovellus toimii hyvin Herokussa ja sitä on helppo käyttää. Myös ulkoasu on siisti.
- Tällä hetkellä uuden käyttäjän pystyy luomaan jättämällä kaikki kentät tyhjiksi. Samoin sisäänkirjautuminen tyhjillä kentillä on edellä mainitun jälkeen mahdollista.
- Myös kurssin luominen tyhjällä otsikolla on mahdollista yhden kerran (kunnes siitä tulee uniikki).

**Koodi**

- Koodi on siististi kirjoitettu, enkä oikein osaa tarjota parannusehdotuksia.
- README on todella kattava ja hienosti toteutettu!

**Muita ajatuksia**

- Kurssien hakutoiminto toimii hyvin, mutta kurssien määrän kasvaessa voisi olla järkevää lisätä mahdollisuus järjestää hakutuloksia esimerkiksi kurssin nimen perusteella. Nyt kurssit taitavat järjestyä listassa ainoastaan siinä järjestyksessä, kun ne ovat luotu tietokantaan?
- Kurssien luomisen yhteydessä voisi tietokantaan tallentaa lisäksi niiden luomisajan. Tämä antaisi myös lisää mahdollisuuksia kurssien hakemiseen tai järjestämiseen.

**Comment by toniramo** [comment]
Kiitos hyvistä kommenteista @TopiasHarjunpaa! Arvostan, että olit käynyt työtäni ajatuksella läpi.

Olit tehnyt oleellisia havaintoja käyttäjäkokemuksen näkökulmasta. Olen ottanut nämä viimeisimmissä muutoksissa huomioon:
- Kenttien validoinnin parantaminen commitissa: https://github.com/toniramo/tso-harjoitustyo/commit/efc7955e73739e37e77d38a506c922d21a2da629
- Kurssihaun parantaminen ja luomisajankohdan lisääminen tietokantaan commitissa: https://github.com/toniramo/tso-harjoitustyo/commit/e4499ef28c7139c5d9eaded3b4aa1e8985f87063
